#!/bin/bash
### BEGIN INIT INFO
# Provides:          icecast-kh
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the icecast-kh audio streaming server daemon
### END INIT INFO
#
# icecast2
#
#        Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#        Modified for Debian
#        by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#
#        Further modified by Keegan Quinn <ice@thebasement.org>
#        for use with Icecast 2
#        
#        Further modified by ssamjh for use with icecast-kh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/icecast-kh-vol/server/ 
DAEMON=/icecast-kh-vol/server/bin/icecast  
NAME=icecast
DESC=icecast

# Set capabilities to allow binding to privileged ports
CAPABILITY_SET="CAP_NET_BIND_SERVICE=+ep"
setcap $CAPABILITY_SET $DAEMON

test -x $DAEMON || exit 0

# Defaults
CONFIGFILE="/icecast-kh-vol/server/etc/icecast.xml"  
USERID=icecast  
GROUPID=icecast  
ENABLE="true"

# Reads config file (will override defaults above)
[ -r "$CONFIGDEFAULTFILE" ] && . $CONFIGDEFAULTFILE

if [ "$ENABLE" != "true" ]; then  
    echo "$NAME daemon disabled - read $CONFIGDEFAULTFILE."
    exit 0
fi

set -e

case "$1" in  
  start)
    echo -n "Starting $DESC: "
    start-stop-daemon --start --quiet --chuid $USERID:$GROUPID \
        --exec $DAEMON -- -b -c $CONFIGFILE
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    # Send TERM after 5 seconds, wait at most 30 seconds.
    start-stop-daemon --stop --oknodo --retry TERM/5/0/30 --quiet --exec $DAEMON
    echo "$NAME."
    ;;
  reload|force-reload)
    echo "Reloading $DESC configuration files."
    start-stop-daemon --stop --signal 1 --quiet --exec $DAEMON
    ;;
  restart)
    echo -n "Restarting $DESC: "
    # Send TERM after 5 seconds, wait at most 30 seconds.
    start-stop-daemon --stop --oknodo --retry TERM/5/0/30 --quiet --exec $DAEMON
    start-stop-daemon --start --quiet --chuid $USERID:$GROUPID \
        --exec $DAEMON -- -b -c $CONFIGFILE
    echo "$NAME."
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
